// jest.setup.ts
jest.setTimeout(30000);
jest.mock('uuid', () => ({
  v4: () => 'test-uuid-v4',
}));
global.env = jest.fn().mockImplementation((key: string) => {
  const envs = {
    PROJECT_CONTACT_NAME: 'Mahmoud Elamrosy',
    PROJECT_CONTACT_URL: 'www.linkedin.com/in',
    PROJECT_CONTACT_EMAIL: 'melamrosy72@gmail.com',
    PROJECT_NAME: 'Makanak',
    PROJECT_DESCRIPTION: 'Manage Service App',
    API_PREFIX: '/api/v1',
    PORT: 3030,
    SOCKET_PORT: 1234,
    REDIS_HOST: 'localhost',
    REDIS_PORT: 6379,
    FRONTEND_URL: 'http://localhost:3000',
    DATABASE_URL: 'mysql://fahd:fahd200@127.0.0.1:3306/mayadeen',
    COOKIE_SECRET: 'awk3m890rdefjc89xzxe3',
    ACCESS_TOKEN_SECRET: 'asdfawefcwewedsc',
    ACCESS_TOKEN_EXPIRE_TIME: 300000,
    REFRESH_TOKEN_SECRET: 'asdfawefcwewedsc_refresh',
    REFRESH_TOKEN_EXPIRE_TIME: 604800,
    RESET_PASSWORD_TOKEN_SECRET: 'lklkdshjdhssdsds',
    FORGET_PASSWORD_TOKEN_EXPIRE_TIME: 300000,
    VERIFY_TOKEN_SECRET: 'asdfawefcwewedsx',
    MULTI_SESSION: 1,
    OTP_INVALIDATE_TIME: 240000,
    HASH_SALT: 13,
    OTP_IGNORE_TIME: 120000,
    PERMISSION_METADATA_KEY: 'permissions',
    ROLE_METADATA_KEY: 'role',
    ACCESS_TOKEN_COOKIE_KEY: 'AccessToken',
    VERIFY_TOKEN_COOKIE_KEY: 'VerifyToken',
    RESET_PASSWORD_TOKEN_COOKIE_KEY: 'ResetPasswordToken',
    DEFAULT_OTP: 1234,
    UPLOADS_PATH: './uploads',
    TEMP_FILE_KEY: 'tempFile',
    INTERCEPTOR_KEY: '#INTERCEPTOR#',
    MAP_URL: 'https://maps.googleapis.com/maps/api/distancematrix/json',
    MAP_TRIALS: 5,
    MAX_PAGE_LIMIT: 40,
    ONE_SIGNAL_APP_KEY: 'MmUyYzEwMmQtZmU3MC00YTY1LThhYzgtMWFmNGJiMDNhY2Q2',
    ONE_SIGNAL_APP_ID: '415bde75-393e-40c0-a276-1c005a845a00',
    ONE_SIGNAL_API_URL: 'https://onesignal.com/api/v1/notifications',
    MAIL_HOST: 'smtp-relay.brevo.com',
    MAIL_PORT: 587,
    MAIL_USER: '7f7eb4001@smtp-brevo.com',
    MAIL_PASSWORD: 'nRF28yzLBgQbNEJS',
    SENDER_EMAIL: 'fahdhakem1234@gmail.com',
    FALLBACK_LANGUAGE: 'en',
    MOYASAR_SECRET_KEY: 'pk_test_ciNbCqwupUsoomZvJfX9ogdXkBRefNT418vE2xpU',
    MOYASAR_PASSWORD: '.',
    MOYASAR_API_BASE: 'https://api.moyasar.com/v1/payments/',
    GOOGLE_MAPS_API_KEY: 'AIzaSyAziY7uCS99_xoWn525o2fXSQER-vHvsxo',
    GOOGLE_API_URL: 'https://maps.googleapis.com/maps/api/distancematrix/json',
    API_GOOGLE_KEY: 'AIzaSyCZ8rNA8xN-yRPX0FgG58zS1eaH7oaBwWs',
    PASSWORD: 'Default@123',
  };
  return envs[key] || '';
});
