import { mapPermissionConfigToRole } from '../../../../../src/globals/helpers/mapRoles.helper';
import { PermissionMap } from '../permissions.provider';

const adminPermissions: PermissionMap = {
  languages: ['post', 'get', 'delete', 'patch'],
  users: ['post', 'get', 'delete', 'patch'],
  roles: ['post', 'get', 'delete', 'patch'],
  profile: ['get', 'patch'],
  permissions: ['get', 'patch'],
  customers: ['get', 'delete', 'patch'],
  banners: ['post', 'get', 'patch', 'delete'],
  branches: ['post', 'get', 'patch', 'delete'],
  categories: ['post', 'get', 'patch', 'delete', 'manage'],
  stores: ['post', 'get', 'patch', 'delete'],
  services: ['post', 'get', 'patch', 'delete'],
  settings: ['get', 'patch'],
  'social-media': ['post', 'get', 'patch', 'delete'],
  'system-notifications': ['get', 'patch'],
  fund: ['post', 'get'],
  coupons: ['post', 'get', 'patch', 'delete'],
  bundles: ['post', 'get', 'patch', 'delete', 'manage'],
  addresses: ['post', 'get', 'patch', 'delete'],
  schedule: ['post', 'get', 'put', 'patch', 'delete', 'manage'],
  orders: ['post', 'get', 'patch', 'delete', 'manage'],
  cities: ['post', 'get', 'patch', 'delete', 'manage'],
  'store-block': ['patch'],
  'store-approval': ['patch'],
  'payment-verification': ['patch'],
  'store-commission': ['patch'],
  'store-zone-pricing': ['patch'],
  'store-managed-by-admin': ['patch'],
  rating: ['get'],
  servicerating: ['get'],
  storerating: ['get'],
  notification: ['post', 'get', 'patch', 'delete', 'manage'],
  statistics: ['get', 'post'],
  'orders/statistics': ['get'],
  specialists: ['get'],
  wallet: ['get'],
  withdraw: ['get', 'patch'],
  transactions: ['get'],
  complaint: ['post', 'get', 'patch', 'delete', 'manage'],
  zones: ['get', 'post', 'patch', 'delete'],
  'variation-templates': ['post', 'get', 'patch', 'delete'],
  'fortune-wheel': ['post', 'get', 'patch', 'delete'],
  logs: ['get'],
  campaigns: ['post', 'get', 'patch', 'delete'],
  'admin-notifications': ['post', 'get', 'delete'],
  'store-templates': ['post', 'get', 'patch', 'delete'],
  delivery: ['post', 'get', 'patch', 'delete'],
  'delivery/withdrawals': ['get', 'patch'],
  'delivery/cash-settlements': ['post', 'get'],
  employees: ['post', 'get', 'patch', 'delete'],
} as const satisfies PermissionMap;

export const AdminRole = {
  id: 1,
  name: { en: 'Admin', ar: 'مشرف' },
  key: 'Admin',
  default: true,
  permissions: mapPermissionConfigToRole(adminPermissions),
};
